version: '2.4'
services:
  burg:
    build: 
      context: .
    image: "burg"
    network_mode: "host"
    runtime: "nvidia"
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ~/.Xauthority:/root/.Xauthority
    environment:
      ROS_MASTER_URI: "http://hsrb:11311"
      ROS_IP: 10.0.0.182
      Xvfb: 99 -screen 0 1920x1080x24
      DISPLAY: $DISPLAY
      QT_X11_NO_MITSHM: 1
    entrypoint: ""
    command: bash -c "source /home/catkin_ws/devel/setup.bash && roslaunch burg_scene_visualizer hsrb_visualize.launch scene_fn:=/home/catkin_ws/src/burg_scene_visualizer/examples/scenes/scene02.yaml"
    stdin_open: true
    tty: true
